#
# Makefile for the linux kernel.
#

obj-y	:= irq.o pcie.o time.o common.o mpp.o addr-map.o
obj-m	:=
obj-n	:=
obj-	:=

obj-$(CONFIG_GENERIC_GPIO) += gpio.o

obj-$(CONFIG_MV_HAL_DRIVERS_SUPPORT) += mv_hal_drivers/
