snd-soc-dove-objs := dove-dma.o
snd-soc-dove-i2s-objs := dove-i2s.o

obj-$(CONFIG_SND_DOVE_SOC) += snd-soc-dove.o
obj-$(CONFIG_SND_DOVE_SOC_I2S) += snd-soc-dove-i2s.o

snd-soc-d2plug-objs := dove-d2plug.o

obj-$(CONFIG_SND_DOVE_SOC_D2PLUG) += snd-soc-d2plug.o

